"""baseline schema (v3)

Revision ID: 4a3c3a03db00
Revises:
Create Date: 2026-06-02 00:13:04.941139

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a3c3a03db00"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadata",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("scan_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="running", nullable=False),
        sa.Column("started_at", sa.String(), nullable=False),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("error_count", sa.Integer(), server_default="0", nullable=True),
        sa.Column("metadata", sa.Text(), server_default="{}", nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.create_index("idx_scans_started_at", ["started_at"], unique=False)
        batch_op.create_index("idx_scans_status", ["status"], unique=False)
        batch_op.create_index("idx_scans_target", ["target"], unique=False)
        batch_op.create_index("idx_scans_type", ["scan_type"], unique=False)

    op.create_table(
        "watch_targets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("watch_type", sa.String(), server_default="domain", nullable=False),
        sa.Column("interval_hours", sa.Integer(), server_default="24", nullable=False),
        sa.Column("last_check", sa.String(), nullable=True),
        sa.Column("next_check", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "notify_on", sa.Text(), server_default='["new", "removed", "modified"]', nullable=True
        ),
        sa.Column("metadata", sa.Text(), server_default="{}", nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target"),
    )
    with op.batch_alter_table("watch_targets", schema=None) as batch_op:
        batch_op.create_index("idx_watch_enabled", ["enabled"], unique=False)
        batch_op.create_index("idx_watch_next_check", ["next_check"], unique=False)
        batch_op.create_index("idx_watch_target", ["target"], unique=False)

    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("parent", sa.String(), nullable=True),
        sa.Column("source", sa.String(), server_default="unknown", nullable=True),
        sa.Column("first_seen", sa.String(), nullable=False),
        sa.Column("last_seen", sa.String(), nullable=False),
        sa.Column("metadata", sa.Text(), server_default="{}", nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "type", "value", name="uq_assets_scan_type_value"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index("idx_assets_scan_id", ["scan_id"], unique=False)
        batch_op.create_index("idx_assets_type", ["type"], unique=False)
        batch_op.create_index("idx_assets_value", ["value"], unique=False)

    op.create_table(
        "certificates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("issuer", sa.String(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("not_before", sa.String(), nullable=False),
        sa.Column("not_after", sa.String(), nullable=False),
        sa.Column("san", sa.Text(), server_default="[]", nullable=True),
        sa.Column("fingerprint_sha256", sa.String(), nullable=True),
        sa.Column("is_expired", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("days_until_expiry", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.create_index("idx_certs_scan_id", ["scan_id"], unique=False)

    op.create_table(
        "config_issues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("affected_asset", sa.String(), nullable=True),
        sa.Column("current_value", sa.String(), nullable=True),
        sa.Column("recommended_value", sa.String(), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config_issues", schema=None) as batch_op:
        batch_op.create_index("idx_issues_category", ["category"], unique=False)
        batch_op.create_index("idx_issues_scan_id", ["scan_id"], unique=False)
        batch_op.create_index("idx_issues_severity", ["severity"], unique=False)

    op.create_table(
        "dns_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("record_type", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dns_records", schema=None) as batch_op:
        batch_op.create_index("idx_dns_scan_id", ["scan_id"], unique=False)

    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(), server_default="tcp", nullable=True),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("banner", sa.Text(), nullable=True),
        sa.Column("product", sa.String(), nullable=True),
        sa.Column("os", sa.String(), nullable=True),
        sa.Column("cpe", sa.Text(), server_default="[]", nullable=True),
        sa.Column("metadata", sa.Text(), server_default="{}", nullable=True),
        sa.Column("source", sa.String(), server_default="shodan", nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.create_index("idx_services_ip", ["ip"], unique=False)
        batch_op.create_index("idx_services_port", ["port"], unique=False)
        batch_op.create_index("idx_services_scan_id", ["scan_id"], unique=False)

    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("vuln_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("affected_asset", sa.String(), nullable=True),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cvss_vector", sa.String(), nullable=True),
        sa.Column("vuln_references", sa.Text(), server_default="[]", nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("epss_score", sa.Float(), nullable=True),
        sa.Column("in_cisa_kev", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("exploit_refs", sa.Text(), server_default="[]", nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vulnerabilities", schema=None) as batch_op:
        batch_op.create_index("idx_vulns_scan_id", ["scan_id"], unique=False)
        batch_op.create_index("idx_vulns_severity", ["severity"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vulnerabilities", schema=None) as batch_op:
        batch_op.drop_index("idx_vulns_severity")
        batch_op.drop_index("idx_vulns_scan_id")

    op.drop_table("vulnerabilities")
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_index("idx_services_scan_id")
        batch_op.drop_index("idx_services_port")
        batch_op.drop_index("idx_services_ip")

    op.drop_table("services")
    with op.batch_alter_table("dns_records", schema=None) as batch_op:
        batch_op.drop_index("idx_dns_scan_id")

    op.drop_table("dns_records")
    with op.batch_alter_table("config_issues", schema=None) as batch_op:
        batch_op.drop_index("idx_issues_severity")
        batch_op.drop_index("idx_issues_scan_id")
        batch_op.drop_index("idx_issues_category")

    op.drop_table("config_issues")
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.drop_index("idx_certs_scan_id")

    op.drop_table("certificates")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index("idx_assets_value")
        batch_op.drop_index("idx_assets_type")
        batch_op.drop_index("idx_assets_scan_id")

    op.drop_table("assets")
    with op.batch_alter_table("watch_targets", schema=None) as batch_op:
        batch_op.drop_index("idx_watch_target")
        batch_op.drop_index("idx_watch_next_check")
        batch_op.drop_index("idx_watch_enabled")

    op.drop_table("watch_targets")
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_index("idx_scans_type")
        batch_op.drop_index("idx_scans_target")
        batch_op.drop_index("idx_scans_status")
        batch_op.drop_index("idx_scans_started_at")

    op.drop_table("scans")
    op.drop_table("metadata")
    # ### end Alembic commands ###
